version: '3.8'

services:
  app:
    image: predigrowee:v2
    depends_on:
      - db
    tty: true
    restart: always
    volumes:
      - ./photos/:/src/photos
    expose:
      - 5000
    environment:
      - FLASK_DEBUG=0
  db:
    image: mysql:5.7
    tty: true
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  db-backup:
    image: databack/mysql-backup
    depends_on:
      - db
    tty: true
    restart: always
    environment:
      DB_DUMP_FREQ: 1440
      DB_DUMP_TARGET: /src/db
      DB_DUMP_KEEP_PERMISSIONS: "false"
      DB_SERVER: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
    volumes:
      - ./dump/:/src/db
  nginx:
    build: ./nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/data:/var/www/acme
      - ./nginx/certs:/var/www/acme/certs