version: '3.8'

services:
  app:
    build: ./app
    tty: true
    restart: always
    command: python -m gunicorn --bind 0.0.0.0:5000 wsgi:application
    volumes:
      - ./app/:/src/app/app
      - ./local/:/src/app/local
      - ./photos/:/src/photos
    ports:
      - 80:5000
  db:
    image: mysql:5.7
    tty: true
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
volumes:
  postgres-data:
