# Do not change the values below!
# If a change is required copy appropriate lines to the /local/config.local.py file and change the values there.

SECRET_KEY = 'please_change_@187%0^&'

# Database connection
DB_HOST = 'localhost'
DB_PORT = 3306
DB_NAME = 'test'
DB_USER = 'test'
DB_PASSWORD = 'test'

# OAuth
GOOGLE_CLIENT_ID = 'google_client_id'
GOOGLE_CLIENT_SECRET = 'google_client_secret'
GOOGLE_CONF_URL = 'https://accounts.google.com/.well-known/openid-configuration'

# Mail config
MAIL_SERVER = 'localhost'
MAIL_PORT = 25
MAIL_USERNAME = 'no-reply@localhost'
MAIL_PASSWORD = 'test'
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEFAULT_SENDER = 'no-reply@localhost'

# Security
SECURITY_PASSWORD_SALT = '9873313545127551081313677346265396239529'

SECURITY_FLASH_MESSAGES = True
SECURITY_PASSWORD_LENGTH_MIN = 8

SECURITY_POST_LOGIN_VIEW = '/'
SECURITY_POST_LOGOUT_VIEW = '/'

SECURITY_REGISTERABLE = True
SECURITY_SEND_REGISTER_EMAIL = True
SECURITY_EMAIL_SUBJECT_REGISTER = 'PrediGrowee - Account registration'
SECURITY_POST_REGISTER_VIEW = 'security.register'
SECURITY_USERNAME_ENABLE = False
SECURITY_USERNAME_REQUIRED = False

SECURITY_CONFIRMABLE = True
SECURITY_CONFIRM_EMAIL_WITHIN = '2 days'
SECURITY_CONFIRM_URL = '/confirm'
SECURITY_EMAIL_SUBJECT_CONFIRM = 'PrediGrowee - Email confirmation'
SECURITY_POST_CONFIRM_VIEW = '/'
SECURITY_AUTO_LOGIN_AFTER_CONFIRM = False
SECURITY_LOGIN_WITHOUT_CONFIRMATION = True

SECURITY_CHANGEABLE = True
SECURITY_POST_CHANGE_VIEW = '/'
SECURITY_SEND_PASSWORD_CHANGE_EMAIL = True
SECURITY_EMAIL_SUBJECT_PASSWORD_CHANGE_NOTICE = 'PrediGrowee - Your password has been changed'

SECURITY_RECOVERABLE = False
SECURITY_TWO_FACTOR = False
SECURITY_TWO_FACTOR_REQUIRED = False
SECURITY_UNIFIED_SIGNIN = False
SECURITY_PASSWORDLESS = False
SECURITY_TRACKABLE = True
SECURITY_WEBAUTHN = False
SECURITY_MULTI_FACTOR_RECOVERY_CODES = False
